<?php

/**
* @file
* Allows mapping to Paragraphs fields.
*/

use \Drupal\Core\Routing\RouteMatchInterface;
use Drupal\feeds_para_mapper\Utility\MapperHelper as MapperHelper;
use Drupal\feeds_para_mapper\Utility\Importer as Importer;
/**
 * Implements hook_help().
 */
function feeds_para_mapper_help($route_name, RouteMatchInterface $route_match){
  switch ($route_name) {
    case 'help.page.feeds_para_mapper':

      $filepath = dirname(__FILE__) . '/README.md';
      if (file_exists($filepath)) {
        $readme = file_get_contents($filepath);
      }
      else {
        $filepath = dirname(__FILE__) . '/README.txt';
        if (file_exists($filepath)) {
          $readme = file_get_contents($filepath);
        }
      }
      if (!isset($readme)) {
        return NULL;
      }
      $moduleHandler = Drupal::moduleHandler();
      if ($moduleHandler->moduleExists('markdown')) {
        $filters = $moduleHandler->invoke('markdown', 'filter_info');
        $info = $filters['filter_markdown'];

        if (function_exists($info['process callback'])) {
          $output = $info['process callback']($readme, NULL);
        }
        else {
          $output = '<pre>' . $readme . '</pre>';
        }
      }
      else {
        $output = '<pre>' . $readme . '</pre>';
      }

      return $output;
  }
}

/**
 * Implements hook_feeds_targets_alter().
 *
 * @param \Drupal\feeds\FieldTargetDefinition[] $targets
 */
function feeds_para_mapper_feeds_targets_alter(&$targets)
{
  foreach ($targets as $name => $target) {
    if($target->getPluginId() === "paragraphs"){
      unset($targets[$name]);
    }
  }
}

/**
 * Implements hook_entity_update().
 */
function feeds_para_mapper_entity_update(Drupal\Core\Entity\EntityInterface $entity)
{
  if(isset($entity->fpm_targets)){
    Importer::finalize($entity);
  }
}

