<?php

namespace Drupal\Tests\feeds_para_mapper\Functional;



/**
 * Minimal test case for the examples module.
 *
 * @group Feeds Paragraphs
 */
class ImportingTest extends FeedsParaMapperTestBase {
  protected function setUp()
  {
    parent::setUp(); // TODO: Change the autogenerated stub
  }
  public function testThings(){
    parent::checkThings();
  }
}